-- 후기 월별로 묶어주고 가장 많이 나온 id가 후기가 가장 많은 공간
-- 각 place별 후기 개수

-- SELECT MONTH(CREATED_AT), MAX(ID)
-- FROM PLACE_REVIEWS
-- GROUP BY MONTH(CREATED_AT)
-- ORDER BY MONTH(CREATED_AT)

-- SELECT PLACE_ID, COUNT(*)
-- FROM PLACE_REVIEWS
-- GROUP BY PLACE_ID

SELECT mon.MONTH(CREATED_AT), p.NAME, cnt.COUNT(*)
FROM (
        SELECT MONTH(CREATED_AT), PLACE_ID, MAX(ID)
        FROM PLACE_REVIEWS
        WHERE CREATED_AT BETWEEN '2018-01-01' AND '2018-12-31'
        GROUP BY MONTH(CREATED_AT)
    ) AS mon
LEFT JOIN PLACES AS p
ON mon.PLACE_ID = p.ID
LEFT JOIN (
    SELECT PLACE_ID, COUNT(*)
    FROM PLACE_REVIEWS
    GROUP BY PLACE_ID
) AS cnt
ON mon.PLACE_ID = cnt.PLACE_ID
ORDER BY mon.MONTH(CREATED_AT), p.NAME;